### ISSUE TITLE
Dependency error

### ISSUE THREAD

**Issue by benjaminniess** [BeAPI/composer-freeze-version#3]
Hi there,

Event after a composer update for some reason I sometimes get this error. The file does exist so I don't really get it.
```
composer freeze-version
PHP Fatal error:  Uncaught Error: Class 'BEA\Composer\MakeStablePlugin\Command\MakeStableCommand' not found in C:\****\public\vendor\bea\composer\make-stable\src\MakeStable.php:39
```

Thanks.
Best,
Princess

**Comment by benjaminniess** [comment]
The thing is: when you run a composer make-stable, "bea/composer/freeze-packages-version-plugin" and "bea/composer/make-stable" are switching to "*@stable" instead of "dev-master".

The solution is to put "dev-master" back, remove the vendor/bea directory and run a new composer update command.

**Comment by MaximeCulea** [comment]
Hi @benjaminniess,
We have made some recent changes. Could you please try :
```
composer clear-cache
composer update
```
This would ensure you have the last version of the package.
Thx

*Edit: it's like you said, by deleting and getting again, it would normally be fixed. Sorry for the inconvenience.*

**Comment by benjaminniess** [comment]
Same same!

`composer make-stable` => all good
'composer update' => 
> Updating bea/composer/freeze-packages-version-plugin (dev-master => 1.0): Downloading (100%)
> Updating bea/composer/make-stable (dev-master => 1.0): Downloading (100%)

`composer freeze-version` => PHP Fatal error:  Uncaught Error: Class 'BEA\Composer\MakeStablePlugin\Command\MakeStableCommand'

**Comment by benjaminniess** [comment]
Good choice, @petitphp is the best element!

**Comment by ghost** [comment]
bye ;)

**Comment by MaximeCulea** [comment]
Is this finally working for you @benjaminniess ?
